---
- name: Install Docker
  hosts: 54.157.42.117
  gather_facts: false
  become: true
  become_user: ubuntu

  tasks:
    - name: Install Docker CE
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
