---
- name: Configure WebServers with Docker
  hosts: 13.61.155.21
  gather_facts: false
  become: True
  become_user: ubuntu
  vars:
    build: latest
    
  tasks:

    - name: Delete running containers
      shell: docker rm -f $(docker ps --all --quiet)

    - name: Delete all Docker Images
      shell: docker rmi -f $(docker images --all --quiet)    


    - name: Pull Docker image
      command: docker pull aodiploma/chilla:{{ build }}

    - name: Run Docker image
      command: docker run -d -p 80:80 443:443 aodiploma/chilla:{{ build }}
