---
- name: Configure Docker image
  hosts: localhost
  become: yes
  become_user: jenkins

  vars:
    docker_image_name: "aodiploma/chilla"
    docker_image_tag_prefix: "v"
    docker_counter_file: "/jenkins/chilla/version_counter.txt"
    docker_container_name: "aodiploma/chilla"
    docker_ports:
      - "443:443"
      - "80:80"
    docker_file_path: "/jenkins/chilla"

  tasks:
  - name: Read the current version counter
    command: cat {{ docker_counter_file }}
    register: version_counter
  
  - name: Trim version counter value
    set_fact:
      trimmed_version_counter: "{{ version_counter.stdout | trim }}"
  
  - name: Login to DockerHub
    shell: echo "$DOCKER_PASSWORD" | docker login -u "aodiploma" --password-stdin
    no_log: true

  - name: Push Docker image to DockerHub
    command: docker push {{ docker_image_name }}:{{ docker_image_tag_prefix }}{{ trimmed_version_counter }}
    register: docker_push
  
  - name: Check if Docker push was successful
    fail:
      msg: "Docker push failed."
    when: docker_push.rc != 0


  
  - name: Remove local Docker image
    command: docker rmi -f {{ docker_image_name }}:{{ docker_image_tag_prefix }}{{ trimmed_version_counter }}
    ignore_errors: yes
