---
- name: Configure Docker image
  hosts: localhost
  become: yes
  become_user: jenkins

  vars:
    docker_image_name: "aodiploma/chilla"
    docker_image_tag_prefix: "v"
    docker_counter_file: "/jenkins/chilla/version_counter.txt"
    docker_container_name: "aodiploma/chilla"
    docker_ports:
      - "443:443"
      - "80:80"
    dockerhub_username: "aodiploma"
    dockerhub_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"  

  tasks:
  - name: Read the current version counter
    slurp:
      src: "{{ docker_counter_file }}"
    register: version_counter

  - name: Trim version counter value
    set_fact:
      trimmed_version_counter: "{{ version_counter.content | b64decode | trim }}"

  - name: Login to DockerHub
    community.docker.docker_login:
      username: "{{ dockerhub_username }}"
      password: "{{ dockerhub_password }}"
      reauthorize: yes

  - name: Push Docker image to DockerHub
    community.docker.docker_image:
      name: "{{ docker_image_name }}"
      tag: "{{ docker_image_tag_prefix }}{{ trimmed_version_counter }}"
      push: yes
      source: local

  - name: Remove local Docker image
    community.docker.docker_image:
      name: "{{ docker_image_name }}"
      tag: "{{ docker_image_tag_prefix }}{{ trimmed_version_counter }}"
      state: absent
    ignore_errors: yes
