name: OWASP ZAP Scan

on:
  [push]

permissions:
  contents: read
  security-events: write

env:
  GITHUB_TOKEN: ${{ secrets.ZAP_TOKEN }}


jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://www.chilla.pp.ua'
          fail_action: false  # Не провалювати завдання при знайдених вразливостях
          cmd_options: '-a'
          

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report/*
          
