on:
  [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
          docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://www.chilla.pp.ua -r testreport.html
