name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Запуск раз на тиждень (понеділок)

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Запуск Docker-контейнера з тестовим додатком
        run: |
          docker build -t myapp:test .
          docker network create zap-network
          docker run -d --network zap-network --name myapp -p 8088:8088 myapp:test
          sleep 10  # Дочекатися запуску додатку

      - name: Запуск OWASP ZAP у фоновому режимі
        run: |
          docker run -d --name zap --network zap-network -v $(pwd):/zap/wrk/:rw -u root zaproxy/zap-stable \
            zap.sh -daemon -host 0.0.0.0 -port 8089
          sleep 30  # Дати ZAP час на запуск

      - name: Запуск сканування Spider
        run: |
          curl "http://zap:8089/JSON/spider/action/scan/?url=http://myapp:8088&maxChildren=10"
          sleep 20  # Чекаємо завершення Spider Scan

      - name: Запуск активного сканування
        run: |
          curl "http://zap:8089/JSON/ascan/action/scan/?url=http://myapp:8088"
          sleep 60  # Дати час на Active Scan

      - name: Генерація звіту
        run: |
          curl "http://zap:8089/OTHER/core/other/htmlreport/" -o report.html

      - name: Завантаження звіту
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
