name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Every Monday
permissions:
  contents: read
  security-events: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.ZAP_TOKEN }}
        with:
          target: 'https://www.chilla.pp.ua'
          fail_action: false
          allow_issue_writing: false
          cmd_options: '-a'

      - name: Check ZAP Report
        run: ls -lah | grep zap_report
         
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAPReport 
          path: zap_report.html

