name: OWASP ZAP Scan

on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker
      run: |
          docker version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read latest version tag
      id: read_version
      run: echo "::set-output name=VERSION::$(cat version_counter.txt)"

    - name: Build Docker image
      run: |
          docker pull aodiploma/chilla:v${{ steps.read_version.outputs.VERSION }}
          docker build -t my-docker-image .



    - name: Build and push Docker image
      run: |
        docker build -t my-app:latest .
        docker run -d -p 8088:8088 my-app:latest

    - name: Pull OWASP ZAP Docker image
      run: docker pull zaproxy/zap-stable

    - name: Run OWASP ZAP scan
      run: |
        docker run -v $(pwd):/zap/wrk/:rw -p 8088:8088 zaproxy/zap-stable zap.sh -daemon -port 8088
        docker exec $(docker ps -q -f ancestor=zaproxy/zap-stable) zap-cli status -t 120
        docker exec $(docker ps -q -f ancestor=zaproxy/zap-stable) zap-cli open-url http://my-app:8088
        docker exec $(docker ps -q -f ancestor=zaproxy/zap-stable) zap-cli spider http://my-app:8088
        docker exec $(docker ps -q -f ancestor=zaproxy/zap-stable) zap-cli active-scan -r http://my-app:8088
        docker exec $(docker ps -q -f ancestor=zaproxy/zap-stable) zap-cli report -o /zap/wrk/report.html -f html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: ./report.html
