name: OWASP ZAP Scan

on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: docker version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Read latest version tag
      id: read_version
      run: echo "VERSION=$(cat version_counter.txt)" >> $GITHUB_ENV

    - name: Create Docker network
      run: docker network create zap-network

    - name: Build and run Docker application
      run: |
        docker pull aodiploma/chilla:v${{ env.VERSION }}
        docker build -t my-app:latest .
        docker run -d --network zap-network --name my-app -p 8088:8088 my-app:latest

    - name: Run OWASP ZAP scan
      run: |
        docker run --rm --network zap-network -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap.sh \
        -cmd -quickurl http://my-app:8088 -quickprogress

    - name: Run OWASP ZAP as daemon
      run: |
        docker run -d --name zap --network zap-network -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap.sh -daemon -host 0.0.0.0 -port 8089
        sleep 15  # Дати ZAP трохи часу на старт

    - name: Generate ZAP report
      run: |
        docker exec zap zap-cli report -o /zap/wrk/report.html -f html



    - name: Check if report exists
      run: ls -lah report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: report.html

