name: OWASP ZAP Scan

on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: docker version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Read latest version tag
      id: read_version
      run: echo "VERSION=$(cat version_counter.txt)" >> $GITHUB_ENV

    - name: Create Docker network
      run: docker network create zap-network

    - name: Build and run Docker application
      run: |
        docker pull aodiploma/chilla:v${{ env.VERSION }}
        docker build -t my-app:latest .
        docker run -d --network zap-network --name my-app -p 8088:8088 my-app:latest

    - name: Run OWASP ZAP as daemon
      run: |
        docker run -d --name zap --network zap-network -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable \
          zap.sh -daemon -host 0.0.0.0 -port 8089
        sleep 10  # Дати ZAP трохи часу

    - name: Debug Docker Network
      run: docker network inspect zap-network || true  # Переконуємось, що всі контейнери в одній мережі

    - name: Check Running Containers
      run: docker ps  # Переконаємось, що `zap` і `my-app` запущені

    - name: Check Open Ports in ZAP
      run: docker exec zap netstat -tlnp || true  # Дивимося, чи реально слухає порт 8089

    - name: Test connection to ZAP inside Docker
      run: |
        docker run --rm --network zap-network byrnedo/alpine-curl -s http://zap:8089/OTHER/core/other/json/version/ \
          && echo "ZAP API is accessible inside the Docker network!" || echo "ZAP API is NOT accessible!"

    - name: Check if ZAP API is available
      run: |
        for i in {1..10}; do
          if curl -s http://zap:8089/OTHER/core/other/json/version/; then
            echo "ZAP is available!"
            exit 0
          fi
          echo "Waiting for ZAP to be available... Attempt $i"
          sleep 10
        done
        echo "ZAP did not start. Exiting."
        docker logs zap  # Вивести логи перед виходом
        exit 1

    - name: Start ZAP Spider Scan
      run: |
        curl "http://zap:8089/JSON/spider/action/scan/?url=http://my-app:8088&maxChildren=10"
        sleep 20  # Чекаємо завершення Spider Scan

    - name: Start ZAP Active Scan
      run: |
        curl "http://zap:8089/JSON/ascan/action/scan/?url=http://my-app:8088"
        sleep 60  # Дати час на Active Scan

    - name: Generate ZAP report
      run: |
        curl "http://zap:8089/OTHER/core/other/htmlreport/" -o report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: report.html
