name: OWASP ZAP Scan

on:
  #push:
  # branches:
  #    - main
  #schedule:
  #  - cron: '0 0 * * 1' # Every Monday
permissions:
  contents: read
  security-events: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4



         
# ZAP 
      - name: ZAP Scan with Official Stable Image
        run: |
           # Pull the official stable ZAP image
            docker pull zaproxy/zap-stable
            docker run --rm \
              zaproxy/zap-stable zap-baseline.py \
              -t https://54.157.42.117/ \
              -I \
              -j \
              --auto 
